### ISSUE TITLE
change color of drop menu list objects

### ISSUE THREAD

**Issue by nikhil191090** [YinTokey/YTDropMenu#1]
i want to change color of  drop down list menus such  and when i tap on first index i want to go to next view controller but it didnt go. please implement diddeselect row at indexpath method .

**Comment by YinTokey** [comment]
Did you tried this method? 
```
- (void)dropMenu:(YTDropMenu *)dropMenu didSelectIndexPath:(NSIndexSet *)selIndexPath
```

**Comment by YinTokey** [comment]
Did you tried this method?    @nikhil191090 
```
- (void)dropMenu:(YTDropMenu *)dropMenu didSelectIndexPath:(NSIndexSet *)selIndexPath
```
